### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by eileenfan** [wbaumann/SmartReceiptsLibrary#59]
//package name: wb.receiptspro
//version: 3.3.3
 android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=wb.receiptspro }
 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
 	at android.app.Activity.startActivityForResult(Activity.java:3390)
 	at android.app.Activity.startActivityForResult(Activity.java:3351)
 	at android.app.Activity.startActivity(Activity.java:3587)
 	at android.app.Activity.startActivity(Activity.java:3555)
 	at co.smartreceipts.android.activities.SettingsActivity.onPreferenceClick(SettingsActivity.java:292)
 	at android.preference.Preference.performClick(Preference.java:952)
 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
 	at android.widget.AdapterView.performItemClick(AdapterView.java:298)
 	at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
 	at android.widget.AbsListView.onKeyUp(AbsListView.java:2929)
 	at android.widget.ListView.commonKey(ListView.java:2267)
 	at android.widget.ListView.onKeyUp(ListView.java:2122)
 	at android.view.KeyEvent.dispatch(KeyEvent.java:2647)
 	at android.view.View.dispatchKeyEvent(View.java:7343)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1388)
 	at android.widget.ListView.dispatchKeyEvent(ListView.java:2097)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:1933)
 	at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1408)
 	at android.app.Activity.dispatchKeyEvent(Activity.java:2384)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1860)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3791)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3774)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3516)
 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3666)
 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:1982)
 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1698)
 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1689)
 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:1959)

**Comment by eileenfan** [comment]
Maybe there's no Market apps like Google Play on the device, especially on emulator. Better to check it.

**Comment by wbaumann** [comment]
Hi @eileenfan . You are correct! This was a bug in an earlier version of the application. Now that we're up to release 4.7.0, however, it has been fixed, so this is on a legacy version. Where did you install the app from? F-Droid? I'll reach out to see if they can submit an updated build.

**Comment by eileenfan** [comment]
I installed it  from F-droid

**Comment by wbaumann** [comment]
Gotcha. Looks like Firebase has not yet processed any of our updates over a year, so we're definitely running on an outdated version there. The main culprit at the moment is Firebase, which we use for OCR scans, since it is not open source. Fortunately, Google plans to change this at "some point":

https://opensource.googleblog.com/2017/05/open-sourcing-firebase-sdks.html

But given that it's unclear when, I'll look into adding a FOSS build flavor for f-droid.

**Comment by wbaumann** [comment]
I'm going to resolve this one to track in this task:

https://github.com/wbaumann/SmartReceiptsLibrary/issues/66

So we can monitor all F-Droid items in one place. Thanks!
